#!/bin/bash

function signal_handler() 
{
	echo "CLEANING UP semaphore && shared memory"
	hako-cleanup
	echo "EXIT"
	exit 0
}

if [ `uname` = "Darwin" ]
then
	export DYLD_LIBRARY_PATH=/usr/local/lib/hakoniwa:${DYLD_LIBRARY_PATH}
fi

trap signal_handler INT TERM

hako-cleanup

hako-master-rust $*
