name: build-ubuntu

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Create directories and Install Dependencies
        run: |
          sudo mkdir -p /usr/local/lib/hakoniwa/
          sudo chown $USER /usr/local/lib/hakoniwa/
          sudo mkdir -p /usr/local/bin/hakoniwa/
          sudo chown $USER /usr/local/bin/hakoniwa/
          sudo apt-get update
          sudo apt-get install -y libc++-dev libc++abi-dev libpython3-dev
          git clone --recursive https://github.com/toppers/hakoniwa-core-cpp-client.git
          cd hakoniwa-core-cpp-client
          # ここで必要に応じてビルドスクリプトを修正
          bash build.bash
          bash install.bash

      - name: Build hakoniwa-conductor
        run: |
          cd main
          bash build.bash
