name: build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Download hakoniwa-core-cpp for Linux
        if:  " (runner.os == 'Linux')"
        run: |
          sudo wget https://github.com/toppers/hakoniwa-core-cpp-client/releases/download/v1.0.2/libshakoc.so -P /usr/local/lib/hakoniwa/
          sudo apt-get update
          sudo apt-get install -y libc++-dev libc++abi-dev libpython3-dev

      - name: Download hakoniwa-core-cpp for Mac(intell)
        if:  " (runner.os == 'macOS')"
        run: |
          sudo wget https://github.com/toppers/hakoniwa-core-cpp-client/releases/download/v1.0.2/libshakoc.dylib -P /usr/local/lib/hakoniwa/

      - name: Build hakoniwa-conductor
        run: |
          cd main
          bash build.bash
